// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ChartPrime

//@version=5
// 该指标使用枢轴点和成交量分析来识别关键的支撑和阻力位。
// 它用动态颜色的方框来可视化这些水平，颜色的强度反映了成交量的强度。
indicator("Support and Resistance (High Volume Boxes) [ChartPrime]", shorttitle = "SR Breaks and Retests [ChartPrime]", overlay=true, max_boxes_count = 50)


// ---------------------------------------------------------------------------------------------------------------------}
// 𝙐𝙎𝙀𝙍 𝙄𝙉𝙋𝙐𝙏𝙎
// ---------------------------------------------------------------------------------------------------------------------{
// 定义用户输入参数，用于调整指标的行为。
int   lookbackPeriod = input.int(20, "Lookback Period", minval=1, group = "Settings") // 回看周期：用于识别枢轴高点和低点的周期长度。
int   vol_len        = input.int(2, "Delta Volume Filter Length", tooltip = "Higher input, will filter low volume boxes" // 成交量过滤长度：用于过滤低成交量区域的长度。
                                                                                                   , group = "Settings")
int   atrPeriod      = input.int(200, "ATR Period", minval=1, group = "Settings") // ATR周期：用于计算区域厚度的ATR周期。
float volFactor      = input.float(2.5, "Volume Factor", minval=0.1, step=0.1, group="Settings", tooltip="成交量因子：数值越大，触发越灵敏(更多区域)；数值越小，触发越迟钝(更少区域)。")
float box_withd      = input.float(1, "Adjust Box Width", maxval = 1000, minval = 0, step = 0.1) // 方框宽度调整：基于ATR调整支撑和阻力区域的宽度。


// ---------------------------------------------------------------------------------------------------------------------}
// 𝙄𝙉𝘿𝙄𝘾𝘼𝙏𝙊𝙍 𝘾𝘼𝙇𝘾𝙐𝙇𝘼𝙏𝙄𝙊𝙉𝙎
// ---------------------------------------------------------------------------------------------------------------------{
// Delta Volume Function
// 计算成交量差额，区分买入和卖出成交量。
upAndDownVolume() =>
    posVol = 0.0 // 正成交量
    negVol = 0.0 // 负成交量
    
    var isBuyVolume = true    // 是否为买入成交量

    // 根据收盘价和开盘价判断是买入还是卖出成交量
    switch
        close > open   => isBuyVolume := true
        close < open   => isBuyVolume := false

    if isBuyVolume
        posVol += volume
    else
        negVol -= volume

    posVol + negVol


// Function to identify support and resistance boxes
// 识别支撑和阻力区域的函数
calcSupportResistance(src, lookbackPeriod, atrPeriod, volFactor) =>
    // Volume
    Vol    = upAndDownVolume() // 获取成交量差额
    vol_hi = ta.highest(Vol/volFactor, vol_len) // 成交量高点阈值
    vol_lo = ta.lowest(Vol/volFactor, vol_len) // 成交量低点阈值

    var float supportLevel      = na // 支撑位
    var float supportLevel_1    = na // 支撑区域下边界
    var float resistanceLevel   = na // 阻力位
    var float resistanceLevel_1 = na // 阻力区域上边界
    var box   sup               = na // 支撑方框
    var box   res               = na // 阻力方框
    var color res_color         = na // 阻力方框颜色
    var color sup_color         = na // 支撑方框颜色
    var float multi             = na

    var bool  brekout_res       = na // 阻力突破
    var bool  brekout_sup       = na // 支撑突破
    var bool  res_holds         = na // 阻力维持
    var bool  sup_holds         = na // 支撑维持

    // Find pivot points
    // 寻找枢轴点
    pivotHigh = ta.pivothigh(src, lookbackPeriod, lookbackPeriod) 
    pivotLow  = ta.pivotlow (src, lookbackPeriod, lookbackPeriod)
    // Box width
    // 计算方框宽度
    atr       = ta.atr(atrPeriod) // 平均真实波幅
    withd     = atr * box_withd // 方框宽度

    // Find support levels with Positive Volume
    // 延迟 lookbackPeriod 根K线后再创建支撑和阻力区域
    // 当发现枢轴低点且成交量为正时，创建支撑区域
    if (not na(pivotLow)) and Vol > vol_hi 

        supportLevel   := pivotLow
        supportLevel_1 := supportLevel-withd       

        topLeft         = chart.point.from_index(bar_index-lookbackPeriod, supportLevel)
        bottomRight     = chart.point.from_index(bar_index, supportLevel_1)

        // 支撑区域的颜色根据成交量强度从透明渐变到绿色
        sup_color      := color.from_gradient(Vol, 0, ta.highest(Vol, 25), color(na), color.new(color.green, 30))

        sup := box.new(
                       top_left     = topLeft, 
                       bottom_right = bottomRight, 
                       border_color = color.green, 
                       border_width = 1, 
                       bgcolor      = sup_color, 
                       text         = "Vol: "+str.tostring(math.round(Vol,2)), 
                       text_color   = chart.fg_color, 
                       text_size    = size.small
                       ) 


    // Find resistance levels with Negative Volume
    // 当发现枢轴高点且成交量为负时，创建阻力区域
    if (not na(pivotHigh)) and Vol < vol_lo
   
        resistanceLevel   := pivotHigh
        resistanceLevel_1 := resistanceLevel+withd

        topLeft            = chart.point.from_index(bar_index-lookbackPeriod, resistanceLevel)
        bottomRight        = chart.point.from_index(bar_index, resistanceLevel_1)

        // 阻力区域的颜色根据成交量强度从红色渐变到透明
        res_color         := color.from_gradient(Vol, ta.lowest(Vol, 25), 0, color.new(color.red, 30), color(na))

        res := box.new(
                       top_left     = topLeft, 
                       bottom_right = bottomRight, 
                       border_color = color.red, 
                       border_width = 1, 
                       bgcolor      = res_color, 
                       text         = "Vol: "+str.tostring(math.round(Vol,2)), 
                       text_color   = chart.fg_color, 
                       text_size    = size.small
                       ) 

    // Adaptive Box Len
    // 动态调整方框的右边界，使其延伸到当前K线
    sup.set_right(bar_index+1)
    res.set_right(bar_index+1)

    // Break of support or resistance conditions
    // 定义支撑和阻力位的突破和维持条件
    brekout_res := ta.crossover(low, resistanceLevel_1) // 价格上穿阻力区域上边界，视为阻力突破
    res_holds   := ta.crossunder(high, resistanceLevel) // 价格下穿阻力位，视为阻力维持

    sup_holds   := ta.crossover(low, supportLevel) // 价格上穿支撑位，视为支撑维持
    brekout_sup := ta.crossunder(high, supportLevel_1) // 价格下穿支撑区域下边界，视为支撑突破

    // Change Color of Support to red if it was break, change color of resistance to green if it was break
    // 如果支撑被突破，则将支撑区域颜色变为红色
    if brekout_sup
        sup.set_bgcolor(color.new(color.red, 80))
        sup.set_border_color(color.red)
        sup.set_border_style(line.style_dashed)

    // 如果支撑维持，则恢复原来的颜色
    if sup_holds
        sup.set_bgcolor(sup_color)
        sup.set_border_color(color.green)
        sup.set_border_style(line.style_solid)

    // 如果阻力被突破，则将阻力区域颜色变为绿色
    if brekout_res
        res.set_bgcolor(color.new(color.green, 80))
        res.set_border_color(color.new(color.green, 0))
        res.set_border_style(line.style_dashed)

    // 如果阻力维持，则恢复原来的颜色
    if res_holds
        res.set_bgcolor(res_color)
        res.set_border_color(color.new(color.red, 0))
        res.set_border_style(line.style_solid)

    [supportLevel, resistanceLevel, brekout_res, res_holds, sup_holds, brekout_sup]


// Calculate support and resistance levels and their breakouts
// 计算支撑和阻力位及其突破状态
[supportLevel,
         resistanceLevel, 
             brekout_res, 
                 res_holds, 
                     sup_holds, 
                         brekout_sup] = calcSupportResistance(close, lookbackPeriod, atrPeriod, volFactor)


// Check if Resistance become Support or Support Become Resistance
// 检查阻力是否转为支撑，或支撑是否转为阻力
var bool res_is_sup = na
var bool sup_is_res = na

// 当阻力被突破时，标记为可能转为支撑
switch
    brekout_res => res_is_sup := true
    res_holds   => res_is_sup := false

// 当支撑被突破时，标记为可能转为阻力
switch
    brekout_sup => sup_is_res := true
    sup_holds   => sup_is_res := false


// ---------------------------------------------------------------------------------------------------------------------}
// 𝙑𝙄𝙎𝙐𝘼𝙇𝙄𝙕𝘼𝙏𝙄𝙊𝙉
// ---------------------------------------------------------------------------------------------------------------------{
// Plot Res and Sup breakouts and holds 
// 在图表上绘制符号，标记支撑和阻力的维持和突破。
// 红色菱形表示阻力维持，可能是卖出信号。
plotchar(res_holds, "Resistance Holds", "◆", 
             color = #e92929,   size = size.tiny, location = location.abovebar, offset = -1)
// 绿色菱形表示支撑维持，可能是买入信号。
plotchar(sup_holds, "Support Holds",    "◆", 
             color = #20ca26, size = size.tiny, location = location.belowbar, offset = -1)

// 绿色菱形表示原阻力位作为支撑维持。
plotchar(brekout_res and res_is_sup[1], "Resistance as Support Holds", "◆", 
             color = #20ca26, size = size.tiny, location = location.belowbar, offset = -1)
// 红色菱形表示原支撑位作为阻力维持。
plotchar(brekout_sup and sup_is_res[1], "Support as Resistance Holds", "◆", 
             color = #e92929,   size = size.tiny, location = location.abovebar, offset = -1)

// Break Out Labels
// 当支撑被突破时，显示 "Break Sup" 标签。
if brekout_sup and not sup_is_res[1]
    label.new(
              bar_index[1], supportLevel[1], 
              text       = "Break Sup", 
              style      = label.style_label_down, 
              color      = #7e1e1e, 
              textcolor  = chart.fg_color, 
              size       = size.small
              )

// 当阻力被突破时，显示 "Break Res" 标签。
if brekout_res and not res_is_sup[1]
    label.new(
              bar_index[1], resistanceLevel[1], 
              text       = "Break Res", 
              style      = label.style_label_up, 
              color      = #2b6d2d, 
              textcolor  = chart.fg_color, 
              size       = size.small
              )


// ◆
// ---------------------------------------------------------------------------------------------------------------------}
